"use server";

import { GoogleGenAI } from "@google/genai";

function getApiKey(customApiKey?: string) {
  const apiKey = customApiKey || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
  if (!apiKey || apiKey.trim() === "") {
    throw new Error("No API key provided. Please open Settings and enter a valid API key for the selected model.");
  }
  return apiKey;
}

async function callModel(modelType: string, apiKey: string, prompt: string) {
  try {
    let outputText = "";
    if (modelType === "gemini") {
      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: "gemini-1.5-flash",
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        config: { responseMimeType: "application/json" },
      });
      outputText = response.text || "";
    } else if (modelType === "claude") {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({
          model: "claude-3-5-sonnet-20241022",
          max_tokens: 4096,
          messages: [{ role: "user", content: prompt + "\n\nRespond ONLY with valid JSON." }]
        })
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      outputText = data.content?.[0]?.text || "";
    } else if (modelType === "openai") {
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
           "Content-Type": "application/json",
           "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: "gpt-4o",
          response_format: { type: "json_object" },
          messages: [{ role: "user", content: prompt }]
        })
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      outputText = data.choices?.[0]?.message?.content || "";
    } else if (modelType === "deepseek") {
      const res = await fetch("https://api.deepseek.com/chat/completions", {
        method: "POST",
        headers: {
           "Content-Type": "application/json",
           "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: "deepseek-chat",
          messages: [{ role: "user", content: prompt }],
          response_format: { type: "json_object" }
        })
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      outputText = data.choices?.[0]?.message?.content || "";
    } else if (modelType === "minimax") {
      const res = await fetch("https://api.minimax.chat/v1/text/chatcompletion_v2", {
        method: "POST",
        headers: {
           "Content-Type": "application/json",
           "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: "abab6.5-chat",
          messages: [{ role: "user", content: prompt }]
        })
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      outputText = data.choices?.[0]?.message?.content || "";
    } else if (modelType === "glm") {
      const res = await fetch("https://open.bigmodel.cn/api/paas/v4/chat/completions", {
        method: "POST",
        headers: {
           "Content-Type": "application/json",
           "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: "glm-4",
          messages: [{ role: "user", content: prompt }]
        })
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      outputText = data.choices?.[0]?.message?.content || "";
    }

    if (!outputText) throw new Error("No response from AI");
    
    let jsonMatch = outputText.match(/```json\n([\s\S]*?)\n```/);
    if (jsonMatch) {
        outputText = jsonMatch[1];
    } else {
        const start = outputText.indexOf("{");
        const end = outputText.lastIndexOf("}");
        if (start !== -1 && end !== -1) {
            outputText = outputText.substring(start, end + 1);
        }
    }

    return { result: JSON.parse(outputText), error: null };
  } catch (error: any) {
    console.error("AI Error:", error);
    return { result: null, error: error.message || "Failed to process text." };
  }
}

export async function detectAIText(text: string, modelType: string, customApiKey?: string) {
  const apiKey = getApiKey(customApiKey);
  const prompt = `Analyze the following text and fragment it into blocks (sentences or paragraphs) based on whether they were likely generated by an AI or written by a human. Be objective and analyze patterns like repetition, predictable phrasing, overly uniform tone, lack of natural variation, and structural consistency. Output the result in JSON format with the following structure:
{
  "score": <number between 0 and 100, where 100 means 100% AI generated overall>,
  "isAI": <boolean, true if likely AI overall, false if mostly human>,
  "indicators": ["<string describing a detected pattern>", "<string>"],
  "explanation": "<detailed summary of your findings>",
  "fragments": [
     { "text": "<exact substring of the original text>", "isAI": <boolean> }
  ]
}

The concatenated "text" fields in the "fragments" array MUST broadly cover the original text. Break it down into reasonable chunks so we can highlight AI-generated parts in yellow and human parts in green. Ensure no Markdown formatting around JSON.

Text to analyze:
${text}`;

  return await callModel(modelType, apiKey, prompt);
}

export async function humanizeText(text: string, tone: string, context: string, modelType: string, customApiKey?: string) {
  const apiKey = getApiKey(customApiKey);
  const toneInstruction = tone === "No writing pattern" 
    ? "\nIMPORTANT: Write the document without any pattern in its words, sentences, or structure that could flag the text as AI generated. Break common AI structures, use highly variable sentence lengths, natural human idiosyncrasies, and unpredictable but coherent phrasing." 
    : `\nThe desired output tone is: ${tone}`;

  const prompt = `You are an expert humanization engine. Rewrite the following text to be more natural and human-like.
Strictly preserve the original meaning, intent, and factual accuracy.
Improve readability, flow, sentence diversity, and tone authenticity.${toneInstruction}
${context ? `\nAdditional user feedback for this iteration: ${context}` : ''}

Output the result in JSON format with the following structure:
{
  "humanizedText": "<the rewritten text>",
  "summaryOfChanges": "<brief explanation of what was changed to make it sound more human and align with the desired tone>"
}

Text to rewrite:
${text}`;

  return await callModel(modelType, apiKey, prompt);
}
